export enum RolesEnum {
  ADMINISTRADOR = 'ADMINISTRADOR',
  GESTOR = 'GESTOR',
  OPERADOR = 'OPERADOR',
  TECNICO = 'TECNICO',
  DOCUMENTACAO = 'DOCUMENTACAO',
  QUALIDADE = 'QUALIDADE',
  INSPETOR = 'INSPETOR',
}
