# Comando para executar compose (API e Banco):
# docker compose up -d
# OU caso precise somente do banco:
# docker compose up -d postgres

services:
  api:
    build:
      context: ./backend
      dockerfile: ../.docker/Dockerfile
    env_file:
      - ./backend/.env.docker
    environment:
      - APP_PORT=3000
    ports:
      - "3000:3000"
    depends_on:
      postgres:
        condition: service_healthy
    restart: always
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost:3000/api/health",
        ]
      interval: 10s
      timeout: 5s
      retries: 5

  postgres:
    image: postgres:18-alpine3.24
    container_name: quimiport_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: quimiport
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d quimiport"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  postgres_data:
