export enum ClasseRiscoOnuEnum {
  EXPLOSIVOS = 1,
  GASES = 2,
  LIQUIDOS_INFLAMAVEIS = 3,
  SOLIDOS_INFLAMAVEIS = 4,
  SUBSTANCIAS_OXIDANTES_E_PEROXIDOS_ORGANICOS = 5,
  SUBSTANCIAS_TOXICAS_E_INFECTANTES = 6,
  MATERIAIS_RADIOATIVOS = 7,
  SUBSTANCIAS_CORROSIVAS = 8,
  SUBSTANCIAS_E_ARTIGOS_PERIGOSOS_DIVERSOS = 9,
}
