export enum StatusCargaEnum {
  CADASTRADA = 'CADASTRADA',
  EM_PREPARACAO = 'EM_PREPARACAO',
  EM_INSPECAO = 'EM_INSPECAO',
  BLOQUEADA = 'BLOQUEADA',
  LIBERADA = 'LIBERADA',
  EM_MOVIMENTACAO = 'EM_MOVIMENTACAO',
  FINALIZADA = 'FINALIZADA',
  CANCELADA = 'CANCELADA',
}
