name: CI

on:
  push:
    branches:
      - "bruno"
      - "fase2/dev"
      - "fase2/main"

  pull_request:
    branches:
      - "bruno"
      - "fase2/dev"
      - "fase2/main"

jobs:
  pipeline:
    name: CI/CD Pipeline
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./backend

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: npm
          cache-dependency-path: ./backend/package-lock.json

      - name: Install Dependencies
        run: npm ci

      - name: Prepare Prisma
        run: npm run prisma:generate

      - name: Build
        run: npm run build

      - name: Execute Tests
        run: npm test

  docker:
    name: Build and Test Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create Docker environment
        working-directory: ./backend
        run: |
          cp .env.docker.example .env.docker

      - name: Build and Start Docker Compose
        run: docker compose up -d --build

      - name: Check containers
        run: docker compose ps

      - name: Wait for services
        run: |
          for i in {1..30}; do
            if docker compose ps | grep -q "healthy"; then
              echo "Waiting for services..."
            fi

            if docker compose ps | grep -q "Up"; then
              echo "Containers are running."
            fi

            sleep 2
          done

      - name: Check PostgreSQL
        run: |
          docker compose exec -T postgres \
            pg_isready -U postgres -d quimiport

      - name: Check API health
        run: |
          curl --fail --retry 10 --retry-delay 2 \
            http://localhost:3000/health

      - name: Show logs on failure
        if: failure()
        run: docker compose logs

      - name: Shutdown
        if: always()
        run: docker compose down -v
